# app/config/security.yml
security:
    providers:
        users_in_memory:
            memory:
                users:
                    ryan:
                        password: $2y$12$ShpvcXP/cYcxuAAK9ClIuOIE.GVYf3Z7qpVPjOeV3FfomwFikkVty #ryanpass
                        roles: 'ROLE_USER'
                    admin:
                        password: $2y$12$AVSEZz0F.M0y4fXpmL77xuJTymm3WOw6KCVfwfKCxP7RDomzUwewO  #kitten
                        roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~
            provider: users_in_memory

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: '^/hello', roles: ROLE_ADMIN }    